export const rolePermissionMap = {
  SUPER_ADMIN: permissionsList.map((p) => p.code),

  ADMIN: [
    "VIEW_USERS",
    "CREATE_USER",
    "UPDATE_USER",
    "DEACTIVATE_USER",
    "VIEW_ROLES",
    "VIEW_REPORTS",
    "EXPORT_REPORT",
    "APPROVE_SALES_ORDER",
    "APPROVE_PURCHASE_ORDER",
    "VIEW_LEDGER",
    "VIEW_PNL",
    "VIEW_BALANCE_SHEET",
    "UPDATE_COMPANY_SETTINGS",
    "CONFIGURE_TAX",
    "CONFIGURE_POS",
  ],

  ACCOUNTANT: [
    "VIEW_LEDGER",
    "CREATE_JOURNAL",
    "REVERSE_JOURNAL",
    "VIEW_PNL",
    "VIEW_BALANCE_SHEET",
    "VIEW_TRIAL_BALANCE",
    "CREATE_INVOICE",
    "VIEW_INVOICE",
    "PAY_VENDOR",
    "VIEW_REPORTS",
    "EXPORT_REPORT",
  ],

  INVENTORY_MANAGER: [
    "CREATE_PRODUCT",
    "UPDATE_PRODUCT",
    "VIEW_PRODUCT",
    "ADJUST_STOCK",
    "VIEW_STOCK",
    "CREATE_PURCHASE_ORDER",
    "RECEIVE_GOODS",
    "VIEW_PURCHASE",
  ],

  SALES: [
    "CREATE_POS_ORDER",
    "HOLD_POS_ORDER",
    "SCAN_BARCODE",
    "VIEW_POS_ORDERS",
    "CREATE_SALES_ORDER",
    "VIEW_SALES_ORDER",
    "APPLY_DISCOUNT",
  ],

  HR_PAYROLL_MANAGER: [
    "CREATE_EMPLOYEE",
    "UPDATE_EMPLOYEE",
    "VIEW_EMPLOYEE",
    "TRACK_ATTENDANCE",
    "PROCESS_PAYROLL",
    "VIEW_PAYROLL_REPORT",
  ],

  VIEWER: [
    "VIEW_REPORTS",
    "VIEW_SALES_ORDER",
    "VIEW_PURCHASE",
    "VIEW_PRODUCT",
    "VIEW_EMPLOYEE",
  ],
};
